// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, public_member_api_docs
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAskrqUtuhdYeBAMwrzHaAiJCXmM00ztEM',
    appId: '1:839908633486:web:9e4d2487a24e9ec9e312df',
    messagingSenderId: '839908633486',
    projectId: 'swiss-medical-flutter-dev',
    authDomain: 'swiss-medical-flutter-dev.firebaseapp.com',
    storageBucket: 'swiss-medical-flutter-dev.appspot.com',
    measurementId: 'G-15KZR77VL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPLT95_bCuli4hw5K8cIBxj2ytq41d_SQ',
    appId: '1:839908633486:android:b66934cc119eb3a0e312df',
    messagingSenderId: '839908633486',
    projectId: 'swiss-medical-flutter-dev',
    storageBucket: 'swiss-medical-flutter-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd_dn1tSb3H41wO2b_JvIzSnxwuj8F7YQ',
    appId: '1:839908633486:ios:6f03786f3a1e6624e312df',
    messagingSenderId: '839908633486',
    projectId: 'swiss-medical-flutter-dev',
    storageBucket: 'swiss-medical-flutter-dev.appspot.com',
    iosBundleId: 'com.swissmedical.appflutter',
  );
}
