// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, public_member_api_docs
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkJs7mLXoJp9p1pNvBGZy9clz3botnnZA',
    appId: '1:178093930947:web:96ac0139087be6b8fc2576',
    messagingSenderId: '178093930947',
    projectId: 'swiss-medical-flutter',
    authDomain: 'swiss-medical-flutter.firebaseapp.com',
    storageBucket: 'swiss-medical-flutter.appspot.com',
    measurementId: 'G-S5FDNDRTEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ss_Inp7JWGCSng3rMmWHorHxpu5yIBc',
    appId: '1:178093930947:android:ad8eb9740147eb31fc2576',
    messagingSenderId: '178093930947',
    projectId: 'swiss-medical-flutter',
    storageBucket: 'swiss-medical-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_EWazU-dx3ULOH4_PlkklafgndxlMdjQ',
    appId: '1:178093930947:ios:aa361db654fc821cfc2576',
    messagingSenderId: '178093930947',
    projectId: 'swiss-medical-flutter',
    storageBucket: 'swiss-medical-flutter.appspot.com',
    iosBundleId: 'swissmedical',
  );
}
