name: api_helper
description: Package to help with API calls.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  collection: ^1.18.0
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  pragma_ui:
    path: ../pragma_ui
  connectivity_plus: ^6.0.5
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  mocktail: ^1.0.4
  test: ^1.19.2
  get_it: ^7.7.0
  flutter_lints: ^3.0.0
